### ISSUE TITLE
Shadertoy .tox files

### ISSUE THREAD

**Issue by OrdinaireX** [medcelerate/FFGLTouchEngine#10]
Hey I have a few tox files that are cut up shaders from shadertoy. When trying to load them, the screen is just black.

Here is an example:

https://drive.google.com/file/d/1obgDypTAbzRD_J5WlNGPaHPEqEvt66SW/view?usp=drive_link

Github doesn't allow .tox files so pardon the drive link.

**Comment by medcelerate** [comment]
You probably want to have a look at the tox. These errors are being produced. You can look at the resolume log file to see these errors.

```
[2024-07-07T21:56:45.861-04:00]   FFGL: TouchEngine Error: Severity: Warning, Location: /tox32/item5/buffA/cubemap1, Description: Cubemaps must have square resolution. Resolution modified.
[2024-07-07T21:56:45.902-04:00]   FFGL: TouchEngine Error: Severity: Error, Location: /tox32/item5/execute1, Description: Traceback (most recent call last):
  File "/tox32/item5/execute1", line 14, in onCreate
AttributeError: 'NoneType' object has no attribute 'par'

[2024-07-07T21:56:45.903-04:00]   FFGL: TouchEngine Error: Severity: Warning, Location: /tox32/item5/buffA/cubemap1, Description: Cubemaps must have square resolution. Resolution modified.
[2024-07-07T21:56:45.942-04:00]   FFGL: TouchEngine Error: Severity: Error, Location: /tox32/item5/execute1, Description: Traceback (most recent call last):
  File "/tox32/item5/execute1", line 14, in onCreate
AttributeError: 'NoneType' object has no attribute 'par'
```

**Comment by OrdinaireX** [comment]
Very interesting, it looks like this is how the Shadertoy .tox handles some of the shader data, I deleted all the unnecessary nodes.

I also found that using a header parameter hid the following data. Thanks for developing such a revolutionary plugin, this will change VJing. Cheers.

**Comment by medcelerate** [comment]
Hmm interesting on the header. Reopen that as a separate issue and tag it
as a feature request.
